### PR TITLE
Feature 1: Print the model view

### PR DESCRIPTION
**Pull request by Wen1234**
According to your advice, I fixed and changed the function of Printing Model. After manual testing, our function successfully passed the test. And in the print preview interface, only the model view.

### CODE REVIEW

**Comment by munterkalmsteiner** [comment]
That looks really good! @sebeder, can you have a look at the implementation?

**Comment by munterkalmsteiner** [comment]
@Wen1234 do you intend to improve the solution based on sebeder's comments?

**Comment by Wen1234** [comment]
Sorry, using typescript to write this code is beyond my ability, so I can't change it.

**Comment by junkerm** [comment]
no further development here, so closing this

**Pull request closed without merging**
