### PR TITLE
Objectif DSL

### PR DESCRIPTION
**Pull request by Daedo**
Added Objectif DSL to Specmate.

### CODE REVIEW

**Comment by sebeder** [comment]
As far as I can see, there are generated files in there. Is that on purpose?
And is there any way I can test this?

**Comment by Daedo** [comment]
Yes, the generated .g and .token files are required by XText. To test the functionality there is an integration test in "ObjectifTest.java"

**Review by sebeder — CHANGES_REQUESTED** [review]
Somehow, the package `com.specmate.modelgeneration.legacy` is missing. Thus, I cannot compile the new bundles. What am I missing there?

**Comment by Daedo** [comment]
> Somehow, the package `com.specmate.modelgeneration.legacy` is missing. Thus, I cannot compile the new bundles. What am I missing there?

I'm not sure. I have made no changes to the legacy code... Can you try to pull it again?

**Review by sebeder — APPROVED** [review]

**Pull request merged**
