### PR TITLE
Feature 4 Wordwarp in node

### PR DESCRIPTION
**Pull request by ruanlx22**
It is about feature 4, Wordwarp in nodes.

**Test case**
**Title:** Feature 4, Wordwarp in nodes
**Description:** This feature will extend name of step node in process models and condition fields of node in CEG model from one line to three line. 
**Test steps:**
1. Open browser and login into Specmate
2. Open graph editor of a process model
3. Add a step node and change the name of node to different length of words
4. Open graph editor of a CEG model
5. Add a node and change the condition field to different length of words

BR,
Group 2

### CODE REVIEW

**Comment by munterkalmsteiner** [comment]
This looks good! I have requested a review by @sebeder. One problem I see is that word wrapping happens in the middle of words (this was not clearly specified in the feature request, how to handle that).

**Comment by sebeder** [comment]
Hello @ruanlx22 and @munterkalmsteiner , yeah, I implemented the issue during a different task. However, line breaks in words are not OK for our customer.

Feel free to have a look at my implementation, which is far from perfect, but working almost as accepted: There is the issue, when the text starts to exceed the maximum total length, the last word is cleared and the ellipsis is shown instead. This make the text usually shorter than before.

**Comment by sebeder** [comment]
Hello again @ruanlx22  and @munterkalmsteiner ,
I just had a look at the implementation as it is now. I'd suggest, for reuse, not to implement an extra component ```truncated-text-three-lines```, but either include this functionality in the existing truncated-text-component or into a multiline-truncated-text-component and give the number of lines or maximum height as ```@Input```-parameter into the component. This way, we could reuse the component in future on different texts in a more flexible way.

**Comment by munterkalmsteiner** [comment]
@ruanlx22 Looking at the code in #308, the code in this pull request, and @sebeder comments, I would suggest you to do the following:
1) checkout #308 
2) fix the outstanding issues mentioned in https://github.com/junkerm/specmate/pull/311#issuecomment-434189055
3) Make sure these requirements are fulfilled: https://github.com/junkerm/specmate/pull/311#pullrequestreview-169630148
4) create a new pull request with #308 as base to merge to 

I think this is the best solution. @sebeder please object if not.

**Comment by sebeder** [comment]
@munterkalmsteiner , this is pefectly fine for me. Please close my pull request to avoid merge conflicts, once you have everything you need.

**Comment by munterkalmsteiner** [comment]
@ruanlx22 talk to me (email, drop by my office) if something is unclear.

**Comment by ruanlx22** [comment]
Hello @munterkalmsteiner and @sebeder, Sorry about replying so late, because of my exam. And very thanks for your suggestions. I will follow the steps to try to deal with the issues.

**Comment by munterkalmsteiner** [comment]
@ruanlx22 , I have talked to @sebeder and, given that his implementation is a bit more flexible, I will merge #308 and close this pull request. Anyway, thank you for your contribution!

**Comment by ruanlx22** [comment]
@munterkalmsteiner , sorry  about that my code still cannot work now. His solution is better than mine and shows me some new idea. @munterkalmsteiner and @sebeder , Thanks for your help.

**Pull request closed without merging**
