### PR TITLE
Refactoring for same implementation in different methods

### PR DESCRIPTION
**Pull request by HeXiangtian**
Extract the same implementation part from different methods, create a new method to achieve this implementation, the original methods calling this new method to achieve original implementation.
Group 1

### CODE REVIEW

**Comment by Wen1234** [comment]
The functions that we change are select and click functions in graphical-editor. We have manually test the functions and it can work as before.

**Comment by HeXiangtian** [comment]
Change setActivateDefaultTool function from public to private

**Comment by munterkalmsteiner** [comment]
I know what needs to be changed. Please fix and update the pull request.

**Comment by HeXiangtian** [comment]
I'm sorry I forgot to push the request before, now you can see the change.

**Comment by munterkalmsteiner** [comment]
I am sorry, this pull request is too messy... I don't see at all what you have changed and what is merged from somewhere else... Please open a new pull request.

**Pull request closed without merging**
