### PR TITLE
Added better naming rule for errors in CEG Nodes

### PR DESCRIPTION
**Pull request by Daedo**
Any validation errors of CEG Nodes will now be named with variable and condition instead of the node name.

### CODE REVIEW

**Comment by junkerm** [comment]
In case of an isolated node, the variable/condition is printed twice, see screenshot. However it is only one unconnected node

image

**Review by junkerm — CHANGES_REQUESTED** [review]
In case of an unconnected node (that is also a duplicate node) the node is listed twice in the error message that refers to the unconnected node. ( see screenshot)
image

**Comment by junkerm** [comment]
I merged with the current develop to see if it's working with the latest ui chagnes. Now the error view isn't showing any errors anymore

image

**Comment by junkerm** [comment]
@Daedo The branch doesn't build on travis
image

... and in fact it does not build locally on machine as well

**Review by junkerm — CHANGES_REQUESTED** [review]
the typescript code is currently not building, neither in travis nor on my machine

**Comment by Daedo** [comment]
It should run now.

**Review by junkerm — APPROVED** [review]
works!

**Pull request merged**
